server:
  port: 9001

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.13:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
