server:
  port: 3377

spring:
  application:
    name: nacos-config-client
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.13:8848


# Nacos 配置规则
# 格式：${prefix}-${spring.profiles.active}.${file-extension}
# 格式说明：
#     prefix 默认为 spring.application.name
#     spring.profiles.active 即为当前环境对应的 profile
#     file-exetension 为配置内容的数据格式，通过spring.cloud.nacos.config.file-extension来配置
