server:
  port: 9527

spring:
  application:
    name: study-springcloud2020-gateway
  cloud:
    gateway: # Gateway配置
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由功能，利用服务名进行路由
      routes:
        - id: payment_routh # 路由ID，没有固定规则，但要求唯一，建议配合服务名称
          # uri: http://127.0.0.1:8002 # 匹配后提供服务的地址
          uri: lb://STUDY-SPRINGCLOUD2020-PROVIDER-PAYMENT # 匹配后提供服务的地址
          predicates:
            - Path=/payment/get/** # 断言，路径匹配的进行路由

        - id: payment_routh2
          # uri: http://127.0.0.1:8001
          uri: lb://STUDY-SPRINGCLOUD2020-PROVIDER-PAYMENT # 匹配后提供服务的地址
          predicates:
            - Path=/payment/create/**

eureka:
  instance:
    hostname: study-springcloud2020-gateway-service
  client:
    # 表示是否将自己注册到Eureka Server中，默认true
    register-with-eureka: true
    # 是否从Eureka Server抓取自己已有的注册信息，默认true。单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka/ 单机Eureka Server
      defaultZone: http://eureka-server7001.com:7001/eureka/,http://eureka-server7002.com:7002/eureka/ # 集群Eureka Server

