server:
  port: 80


spring:
  application:
    name: study-springcloud2020-consumer-order

eureka:
  client:
    # 表示是否将自己注册到Eureka Server中，默认true
    register-with-eureka: false
    # 是否从Eureka Server抓取自己已有的注册信息，默认true。单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka/ 单机Eureka Server
      defaultZone: http://eureka-server7001.com:7001/eureka/,http://eureka-server7002.com:7002/eureka/ # 集群Eureka Server

ribbon:
  # 建立连接超时时间
  ReadTimeout: 5000
  # 建立连接后，请求超时时间
  ConnectTimeout: 5000

logging:
  level:
    # Feign日志以哪个日志级别监控哪个接口
    com.wez.springcloud.service.OpenFeignOrderService: debug
